declare -i INDEX=180

BUNDLE_DIR="/var/lib/pulp/exports/bundles"
BASEURL="https://10.0.93.8/file/satelite6/20160601-"
read -r -a FILELIST <<< $(ls $BUNDLE_DIR | grep ^newbundle.[0-9]*$)

while [ $INDEX -lt ${#FILELIST[@]} ]
do
  if [ -f $BUNDLE_DIR/${FILELIST[INDEX]}.transfer ]
  then
    echo "Skipping $BUNDLE_DIR/${FILELIST[INDEX]}, as it already has a transfer file present."
    INDEX+=1
    continue
  fi
  echo Converting Bundle ${FILELIST[INDEX]}
  echo "This is a file generated by Red Hat in order to assist scanners, which are having trouble reading the verified Red Hat data below.  Please contact taylor@redhat.com if you have any concerns or issues." > $BUNDLE_DIR/${FILELIST[INDEX]}.txt
  md5sum $BUNDLE_DIR/${FILELIST[INDEX]} >> $BUNDLE_DIR/${FILELIST[INDEX]}.txt
  echo >> $BUNDLE_DIR/${FILELIST[INDEX]}.txt
  cat $BUNDLE_DIR/${FILELIST[INDEX]} | base64 >> $BUNDLE_DIR/${FILELIST[INDEX]}.txt
  rm $BUNDLE_DIR/${FILELIST[INDEX]}
  echo Uploading Bundle ${FILELIST[INDEX]}
  curl -k -f -T $BUNDLE_DIR/${FILELIST[INDEX]}.txt $BASEURL${FILELIST[INDEX]}.txt > $BUNDLE_DIR/${FILELIST[INDEX]}.transfer

  INDEX+=1
done
